# Generated by Django 3.2.3 on 2021-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id_det_ent', models.IntegerField(primary_key=True, serialize=False)),
                ('retiro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'detalle_entrega',
                'managed': False,
            },
        ),
    ]
