-- Generated by Oracle SQL Developer Data Modeler 4.0.2.840
--   at:        2021-04-21 22:08:12 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE DETALLE_PRESCRIPCION
  (
    id_pres        NUMERIC (5) NOT NULL ,
    id_med         NUMERIC (5) NOT NULL ,
    descripcion    VARCHAR (100) NOT NULL ,
    cantidad       NUMERIC (2) NOT NULL
  ) ;
ALTER TABLE DETALLE_PRESCRIPCION ADD CONSTRAINT DETALLE_PRESCRIPCION_PK PRIMARY KEY ( id_pres, id_med ) ;

CREATE TABLE ENTREGA_MEDICAMENTO
  (
    id_entrega NUMERIC (7) NOT NULL ,
    id_pres    NUMERIC (5) NOT NULL ,
    rut_func   NUMERIC (8) NOT NULL ,
    fecha      DATE NOT NULL
  ) ;
ALTER TABLE ENTREGA_MEDICAMENTO ADD CONSTRAINT ENTREGA_MEDICAMENTO_PK PRIMARY KEY ( id_entrega ) ;

CREATE TABLE FUNCIONARIO
  (
    rut_func    NUMERIC (8) NOT NULL ,
    dv          CHAR (1) NOT NULL ,
    pri_nombre  VARCHAR (50) NOT NULL ,
    seg_nombre  VARCHAR (50) NOT NULL ,
    ape_paterno VARCHAR (50) NOT NULL ,
    ape_materno VARCHAR (50) NOT NULL ,
    user_func   VARCHAR (50) NOT NULL ,
    contra      VARCHAR (50) NOT NULL
  ) ;
ALTER TABLE FUNCIONARIO ADD CHECK ( dv IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K', 'k')) ;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY ( rut_func ) ;

CREATE TABLE MEDICAMENTO
  (
    id_med  NUMERIC (5) NOT NULL ,
    nombre  VARCHAR (50) NOT NULL ,
    detalle VARCHAR (100) NOT NULL ,
    gramaje VARCHAR (10) NOT NULL ,
    stock   NUMERIC (100) NOT NULL ,
    merma   NUMERIC (100) NOT NULL
  ) ;
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDICAMENTO_PK PRIMARY KEY ( id_med ) ;

CREATE TABLE MEDICO
  (
    rut_medico   NUMERIC (8) NOT NULL ,
    dv           CHAR (1) NOT NULL ,
    pri_nombre   VARCHAR (50) NOT NULL ,
    seg_nombre   VARCHAR (50) NOT NULL ,
    ape_paterno  VARCHAR (50) NOT NULL ,
    ape_materno  VARCHAR (50) NOT NULL ,
    especialidad VARCHAR (50) NOT NULL ,
    user_medic   VARCHAR (50) NOT NULL ,
    contra       VARCHAR (50) NOT NULL
  ) ;
ALTER TABLE MEDICO ADD CHECK ( dv IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K', 'k')) ;
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_PK PRIMARY KEY ( rut_medico ) ;

CREATE TABLE PACIENTE
  (
    rut_pac         NUMERIC (8) NOT NULL ,
    dv              CHAR (1) NOT NULL ,
    pri_nombre      VARCHAR (50) NOT NULL ,
    seg_nombre      VARCHAR (50) NOT NULL ,
    ape_paterno     VARCHAR (50) NOT NULL ,
    ape_materno     VARCHAR (50) NOT NULL ,
    edad            NUMERIC (3) NOT NULL ,
    sexo            CHAR (1) NOT NULL ,
    telefono        NUMERIC (8) NOT NULL ,
    email           VARCHAR (100) NOT NULL ,
    inscripcion_fam VARCHAR (50) NOT NULL
  ) ;
ALTER TABLE PACIENTE ADD CHECK ( dv IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K', 'k')) ;
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( rut_pac ) ;

CREATE TABLE PRESCRIPCION
  (
    id_pres    NUMERIC (5) NOT NULL ,
    rut_medico NUMERIC (8) NOT NULL ,
    rut_pac    NUMERIC (8) NOT NULL
  ) ;
ALTER TABLE PRESCRIPCION ADD CONSTRAINT PRESCRIPCION_PK PRIMARY KEY ( id_pres ) ;

CREATE TABLE RESERVA_MEDICAMENTO
  (
    id_reserva NUMERIC (5) NOT NULL ,
    id_entrega NUMERIC (7) NOT NULL ,
    detalle    VARCHAR (100) NOT NULL
  ) ;
ALTER TABLE RESERVA_MEDICAMENTO ADD CONSTRAINT RESERVA_MEDICAMENTO_PK PRIMARY KEY ( id_reserva ) ;

ALTER TABLE DETALLE_PRESCRIPCION ADD CONSTRAINT DET_PRES_MED_FK FOREIGN KEY ( id_med ) REFERENCES MEDICAMENTO ( id_med ) ;

ALTER TABLE DETALLE_PRESCRIPCION ADD CONSTRAINT DET_PRES_PRESCRIP_FK FOREIGN KEY ( id_pres ) REFERENCES PRESCRIPCION ( id_pres ) ;

ALTER TABLE ENTREGA_MEDICAMENTO ADD CONSTRAINT ENT_MED_FUNC_FK FOREIGN KEY ( rut_func ) REFERENCES FUNCIONARIO ( rut_func ) ;

ALTER TABLE ENTREGA_MEDICAMENTO ADD CONSTRAINT ENT_MED_PRESC_FK FOREIGN KEY ( id_pres ) REFERENCES PRESCRIPCION ( id_pres ) ;

ALTER TABLE PRESCRIPCION ADD CONSTRAINT PRESCRIPCION_MEDICO_FK FOREIGN KEY ( rut_medico ) REFERENCES MEDICO ( rut_medico ) ;

ALTER TABLE PRESCRIPCION ADD CONSTRAINT PRESCRIPCION_PACIENTE_FK FOREIGN KEY ( rut_pac ) REFERENCES PACIENTE ( rut_pac ) ;

ALTER TABLE RESERVA_MEDICAMENTO ADD CONSTRAINT RES_MED_ENT_MED_FK FOREIGN KEY ( id_entrega ) REFERENCES ENTREGA_MEDICAMENTO ( id_entrega ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
